# Generated by Django 4.1 on 2024-02-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_visit_excluding_today',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
