version: '3.8'

services:
  web:
    build: ./Django_App/prominent_profiles
    image: ghcr.io/meeky37/fy-project/web:latest
    command: >
      sh -c "python manage.py collectstatic --noinput &&
                  python manage.py migrate &&
                  gunicorn prominent_profiles.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./Django_App/prominent_profiles
      - media_volume:/app/nlp_processor/media
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RUNNING_IN_DOCKER=${RUNNING_IN_DOCKER}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - BING_API_KEY=${ING_API_KEY}

  nginx:
    build:
      context: ./
      dockerfile: Django_App/prominent_profiles/nginx/Dockerfile.nginx
    image: ghcr.io/meeky37/fy-project/nginx:latest
    volumes:
#      - ./Django_App/prominent_profiles #Remove later and see if actually required.
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: