EXPONENTIAL_K_VALUE = 3
MENTION_REQ_PER = 0.20
ENTITY_THRESHOLD_PERCENT = 0.30
MERGE_REMOVAL_INDICATOR = -200
COMBINED_REMOVAL_INDICATOR = -100
COMBINED_CLUSTER_ID_SEPARATOR = '0000'
SIMILAR_SEARCH_DAYS = 3
PREVIEW_IMG_TIMEOUT = 3
