# Generated by Django 4.1 on 2023-12-11 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('app_visible', models.BooleanField(default=False)),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles_app.article')),
            ],
        ),
        migrations.CreateModel(
            name='OverallSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bound', models.IntegerField()),
                ('linear_neutral', models.DecimalField(decimal_places=2, max_digits=5)),
                ('linear_positive', models.DecimalField(decimal_places=2, max_digits=5)),
                ('linear_negative', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exp_neutral', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exp_positive', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exp_negative', models.DecimalField(decimal_places=2, max_digits=5)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_app.article')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_app.entity')),
            ],
        ),
        migrations.CreateModel(
            name='BoundMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bound_start', models.IntegerField()),
                ('bound_end', models.IntegerField()),
                ('avg_neutral', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_positive', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_negative', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bound_text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_app.article')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_app.entity')),
            ],
        ),
        migrations.CreateModel(
            name='BingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('web_search_url', models.CharField(max_length=255)),
                ('bing_id', models.CharField(max_length=255)),
                ('contractual_rules', models.JSONField()),
                ('entity_type_display_hint', models.CharField(max_length=255)),
                ('entity_type_hints', models.JSONField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_app.entity')),
            ],
        ),
    ]
