# Generated by Django 4.1 on 2023-12-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='minhash_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
