# Generated by Django 4.1 on 2023-12-03 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0002_remove_entity_source_article_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('web_search_url', models.CharField(max_length=255)),
                ('bing_id', models.CharField(max_length=255)),
                ('contractual_rules', models.JSONField()),
                ('entity_type_display_hint', models.CharField(max_length=255)),
                ('entity_type_hints', models.JSONField()),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_app.entity')),
            ],
        ),
    ]
