# Generated by Django 4.1 on 2023-12-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0003_bingentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='app_visible',
            field=models.BooleanField(default=True),
        ),
    ]
