# Generated by Django 4.1 on 2023-12-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0004_article_tfidf_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='minhash_signature',
        ),
        migrations.RemoveField(
            model_name='article',
            name='similar_articles',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tfidf_vector',
        ),
    ]
