# Generated by Django 4.1 on 2023-12-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0004_entity_app_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='app_visible',
            field=models.BooleanField(default=False),
        ),
    ]
