# Generated by Django 4.1 on 2023-12-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0006_article_similar_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='similar_articles',
        ),
        migrations.AddField(
            model_name='article',
            name='similar_article',
            field=models.ManyToManyField(blank=True, to='profiles_app.article'),
        ),
    ]
