# Generated by Django 4.1 on 2023-12-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0009_alter_article_similar_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='similar_articles',
            field=models.ManyToManyField(blank=True, limit_choices_to={'similar_articles__isnull': False}, to='profiles_app.article'),
        ),
    ]
