# Generated by Django 4.1 on 2023-12-30 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0011_remove_article_similar_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='source_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_app.article'),
        ),
    ]
