# Generated by Django 4.1 on 2024-01-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0012_entity_view_count_alter_entity_source_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_dt', models.DateField(auto_now_add=True)),
                ('view_time', models.TimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_app.entity')),
            ],
        ),
    ]
