# Generated by Django 4.1 on 2024-01-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0016_remove_entity_overallsentiment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
