# Generated by Django 4.1 on 2024-01-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0017_article_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreEntitySimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignore_relationships_a', to='profiles_app.entity')),
                ('entity_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignore_relationships_b', to='profiles_app.entity')),
            ],
            options={
                'unique_together': {('entity_a', 'entity_b')},
            },
        ),
    ]
