# Generated by Django 4.1 on 2024-01-22 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles_app', '0018_ignoreentitysimilarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('master_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_logs', to='profiles_app.entity')),
                ('secondary_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_app.entity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
