# Generated by Django 4.1 on 2024-01-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0020_entityhistory_delete_entitymergelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='similar_rejection',
            field=models.BooleanField(default=False),
        ),
    ]
