# Generated by Django 4.1 on 2024-02-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0025_alter_entity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingentity',
            name='improved_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
