# Generated by Django 4.1 on 2024-02-27 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_processor', '0014_alter_articlestatistics_fuzzy_hash'),
        ('profiles_app', '0026_bingentity_improved_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nlp_processor.processedfile'),
        ),
    ]
