# Generated by Django 4.1 on 2024-03-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0027_article_source_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarEntityPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('entity_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_pair_a', to='profiles_app.entity')),
                ('entity_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_pair_b', to='profiles_app.entity')),
            ],
        ),
        migrations.AddIndex(
            model_name='similarentitypair',
            index=models.Index(fields=['entity_a', 'entity_b'], name='profiles_ap_entity__178ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='similarentitypair',
            index=models.Index(fields=['entity_b', 'entity_a'], name='profiles_ap_entity__b51708_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='similarentitypair',
            unique_together={('entity_a', 'entity_b')},
        ),
    ]
