# Generated by Django 4.1 on 2024-03-08 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0028_similarentitypair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityhistory',
            name='merged_into',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles_app.entity'),
        ),
    ]
