# Generated by Django 4.1 on 2024-03-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0029_alter_entityhistory_merged_into'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bingentity',
            options={'verbose_name': 'Bing entity', 'verbose_name_plural': 'Bing entities'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='entityhistory',
            options={'verbose_name': 'Entity history', 'verbose_name_plural': 'Entity histories'},
        ),
        migrations.AlterModelOptions(
            name='ignoreentitysimilarity',
            options={'verbose_name': 'Ignore entity similarity', 'verbose_name_plural': 'Ignore entity similarities'},
        ),
    ]
