# Generated by Django 4.1 on 2023-12-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('media_path', models.CharField(max_length=255)),
                ('nlp_applied', models.BooleanField(default=False)),
            ],
        ),
    ]
