# Generated by Django 4.1 on 2024-01-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_processor', '0002_bounderrors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoundErrors',
            new_name='BoundError',
        ),
    ]
