# Generated by Django 4.1 on 2024-01-25 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_processor', '0004_articlestatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarArticlePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.IntegerField()),
                ('article1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article1', to='nlp_processor.articlestatistics')),
                ('article2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article2', to='nlp_processor.articlestatistics')),
            ],
        ),
    ]
