# Generated by Django 4.1 on 2024-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_processor', '0008_alter_similararticlepair_and_diff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similararticlepair',
            name='and_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='in_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='is_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='it_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='of_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='simpsond_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='terms_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='that_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='the_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='to_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='vocd_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='with_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='words_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='similararticlepair',
            name='yulek_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
