# Generated by Django 4.1 on 2024-01-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_processor', '0009_alter_similararticlepair_and_diff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='similararticlepair',
            name='average_count_diff',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
