# Generated by Django 4.1 on 2024-01-29 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0021_article_similar_rejection'),
        ('nlp_processor', '0011_rename_average_count_diff_similararticlepair_avg_count_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounderror',
            name='article',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles_app.article'),
        ),
    ]
