# Generated by Django 4.1 on 2024-03-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_processor', '0014_alter_articlestatistics_fuzzy_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlestatistics',
            options={'verbose_name': 'Article statistic', 'verbose_name_plural': 'Article statistics'},
        ),
    ]
