<template>
  <div class="about">
    <h1>About Prominent Profiles</h1>
 <div id="disclaimer" class="disclaimer">
   Prominent Profiles is a new way to explore and share diverse viewpoints of important figures.
   Unlike traditional methods that categorise media sources on a spectrum of left to right-wing, we
   delve deeper with target-dependent sentiment analysis enabling us to assess the
   sentiment directed specifically towards each individual.

   Our unique approach identifies articles where a figure is mentioned in at least 20% of sentences,
   ensuring comprehensive coverage that goes beyond the surface-level implications of headlines.
   Each analysed article is added to the individual's profile on our platform, creating a rich,
   multidimensional view of their public perception.
 </div>
 <div id="disclaimer" class="disclaimer">
    <h2>Disclaimer</h2>

    <h3>Experimental Nature</h3>
    <p>The sentiment analysis functionality provided on the "Prominent Profiles" web application is
      an experimental feature designed to offer insights into the general sentiment of articles.
      This feature uses complex algorithms and natural language processing techniques to attempt to
      understand and interpret the sentiment conveyed in text. Users must recognise that this
      technology is still under development and may not always accurately reflect the nuances
      of human emotions or the intended sentiment of the articles.
    </p>
    <h3>Subjectivity of Sentiment</h3>
    <p>Sentiment analysis is inherently subjective, with interpretations that can vary widely among individuals. The results produced by our sentiment analysis feature are generated by automated processes that do not involve human judgment. As such, these results should be viewed as indicative rather than definitive, and users are encouraged to apply their own judgment and interpretation.</p>

    <h3>Limitation of Liability</h3>
    <p>"Prominent Profiles" and its developers make no representations or warranties of any kind,
      express or implied, about the sentiment analysis feature's completeness, accuracy,
      reliability, suitability, or availability. Therefore, any reliance on such information is
      strictly at your own risk. We disclaim all liability and responsibility arising from any
      reliance placed on the sentiment analysis results by any user of our web application or
      anyone who may be informed of its contents.
    </p>
    <h3>No Endorsement</h3>
    <p>The sentiment analysis provided by "Prominent Profiles" does not constitute an endorsement of any article, author, or opinion. The feature is intended for informational purposes only, to offer a technological perspective on the sentiment of texts. Users are advised to consider a wide range of opinions and conduct their own research when forming their views.</p>

    <h3>Feedback and Improvements</h3>
    <p>We are attentive to any user feedback that may help us improve the accuracy and
      reliability of our sentiment analysis features.
      If you have suggestions or feedback about the sentiment analysis or any other aspect of
      <strong>Prominent Profiles</strong>, please do not hesitate to contact us at
      <a href="mailto:info@prominentprofiles.com">info@prominentprofiles.com</a>.
    </p>

</div>

<div id="PrivacyPolicy">
  <h2>Privacy Policy</h2>
  <p>Read our Privacy Policy to understand how we collect, use, and protect your information.</p>
  <router-link to="/privacypolicy">Privacy Policy</router-link>
</div>

<div id="Credits">
  <h2>Git Repository</h2>
  <p>Visit our GitHub repository for acknowledgments behind Prominent Profiles.</p>
  <a href="https://github.com/meeky37/FY-Project">Git Repo</a><br>
  </div>

  </div>
</template>
<script setup>
</script>
<style scoped>
.disclaimer{
  width: 75vw;
  margin-left: auto;
  margin-right: auto;
}
</style>
