<template>
  <div class="about">
    <h1>About Prominent Profiles</h1>
 <div id="disclaimer">
    <h2>Disclaimer</h2>

    <h3>Experimental Nature</h3>
    <p>The sentiment analysis functionality provided on the "Prominent Profiles" web application is an experimental feature designed to offer insights into the general sentiment of articles. This feature uses complex algorithms and natural language processing techniques to attempt to understand and interpret the sentiment conveyed in text. It is important for users to recognize that this technology is still under development and may not always accurately reflect the nuances of human emotions or the intended sentiment of the articles.</p>

    <h3>Subjectivity of Sentiment</h3>
    <p>Sentiment analysis is inherently subjective, with interpretations that can vary widely among individuals. The results produced by our sentiment analysis feature are generated by automated processes that do not involve human judgment. As such, these results should be viewed as indicative rather than definitive, and users are encouraged to apply their own judgment and interpretation.</p>

    <h3>Limitation of Liability</h3>
    <p>"Prominent Profiles" and its developers make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the sentiment analysis feature. Any reliance you place on such information is therefore strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on the results of the sentiment analysis by any user of our web application, or by anyone who may be informed of its contents.</p>

    <h3>No Endorsement</h3>
    <p>The sentiment analysis provided by "Prominent Profiles" does not constitute an endorsement of any article, author, or opinion. The feature is intended for informational purposes only, to offer a technological perspective on the sentiment of texts. Users are advised to consider a wide range of opinions and conduct their own research when forming their views.</p>

    <h3>Feedback and Improvements</h3>
    <p>We are attentive to any user feedback that may help us to improve the accuracy and
      reliability of our sentiment analysis features.
      If you have suggestions or feedback about the sentiment analysis or any other aspect of
      "Prominent Profiles," please do not hesitate to contact us. EMAIL ADDRESS HERE</p>
</div>
<div id="Credits">
  <h2>Credits</h2>
    <a href="https://github.com/meeky37/FY-Project">Git Repo</a><br>
    <a href="https://logo.com">Logo: Logo.com</a><br>
    <a href="https://trafilatura.readthedocs.io/en/latest/index.html">Trafilatura</a><br>
    <a href="https://pypi.org/project/fastcoref/">Fast Coref</a><br>
    <a href="https://www.nltk.org/">NLTK</a><br>
    <a href="https://pypi.org/project/NewsSentiment/">News Sentiment</a><br>
    <a href="https://textblob.readthedocs.io/en/dev/">TextBlob</a><br>
    <a href="https://pypi.org/project/django-admin-shortcuts/">Django Admin Shortcuts</a><br>
    <p>Add other modules/packages here - review properly</p>
  </div>
  </div>
</template>
<script setup>
</script>
