version: '3.8'

services:
  web:
    image: ghcr.io/meeky37/fy-project/web:latest
    command: >
      sh -c "chmod -R 777 /app/nlp_processor/media /app/static &&
                  python manage.py collectstatic --noinput &&
                  python manage.py migrate &&
                  gunicorn prominent_profiles.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - media_volume:/app/nlp_processor/media
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RUNNING_IN_DOCKER=${RUNNING_IN_DOCKER}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - BING_API_KEY=${BING_API_KEY}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

  nginx:
    image: ghcr.io/meeky37/fy-project/nginx:latest
    volumes:
#      - .:/app
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./letsencrypt:/etc/letsencrypt
      - ./lib/letsencrypt:/var/lib/letsencrypt
      - ./webroot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./lib/letsencrypt:/var/lib/letsencrypt
      - ./webroot:/var/www/certbot
      - ./nginx:/etc/nginx:ro
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 1d & wait $${!}; done;'"
    command: >
      certonly --webroot --webroot-path=/var/www/certbot
      --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email
      -d prominentprofiles.com -d www.prominentprofiles.com

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  celery:
    image: ghcr.io/meeky37/fy-project/web:latest
    user: django-user
    command: ["celery", "-A", "prominent_profiles", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis

  celerybeat:
    image: ghcr.io/meeky37/fy-project/web:latest
    user: django-user
    command: ["celery", "-A", "prominent_profiles", "beat", "--loglevel=info", "--scheduler",
              "django_celery_beat.schedulers:DatabaseScheduler"]
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume: