version: '3.8'

services:
  web:
    image: ghcr.io/meeky37/fy-project/web:latest
    command: >
      sh -c "python manage.py collectstatic --noinput &&
                  python manage.py migrate &&
                  gunicorn prominent_profiles.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - media_volume:/app/nlp_processor/media
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - RUNNING_IN_DOCKER=${RUNNING_IN_DOCKER}
      - SECRET_KEY=${SECRET_KEY}

  nginx:
    image: ghcr.io/meeky37/fy-project/nginx:latest
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
