version: '3.8'

services:
  web:
    image: ghcr.io/meeky37/fy-project/web:latest
    command: >
      sh -c "python manage.py collectstatic --noinput &&
                  python manage.py migrate &&
                  gunicorn prominent_profiles.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - media_volume:/app/nlp_processor/media
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - RUNNING_IN_DOCKER=${RUNNING_IN_DOCKER}
      - SECRET_KEY=${SECRET_KEY}

  vuejs:
    build:
      context: ../Vue_js/prominent_profiles
    ports:
      - "8080:80" # Expose Vue.js app on port 8080 on the host (was at 8080 when local).
    depends_on:
      - web

  nginx:
    image: ghcr.io/meeky37/fy-project/nginx:latest
    volumes:
#      - .:/app
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./letsencrypt:/etc/letsencrypt
      - ./lib/letsencrypt:/var/lib/letsencrypt
      - ./webroot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - vuejs

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./lib/letsencrypt:/var/lib/letsencrypt
      - ./webroot:/var/www/certbot
      - ./nginx:/etc/nginx:ro
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 1d & wait $${!}; done;'"
    command: >
      certonly --webroot --webroot-path=/var/www/certbot
      --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email
      --staging -d prominentprofiles.com -d www.prominentprofiles.com

volumes:
  postgres_data:
  static_volume:
  media_volume: